services:
  postgres:
    image: postgres:latest
    container_name: camTracker-postgres
    hostname: postgres
    ports:
      - "6543:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cam_tracker
    volumes:
      - cam_tracker-postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - camTracker-network

volumes:
  cam_tracker-postgres-data:

networks:
  camTracker-network:
    driver: bridge